#:schema node_modules/wrangler/config-schema.json
name = "hono-avatars"
main = "src/index.ts"
compatibility_date = "2024-07-25"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "KV"
id = "${KV_NAMESPACE_ID}"
preview_id = "${KV_NAMESPACE_PREVIEW_ID}"

[vars]
CACHE_ENABLED = true
